//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BusquedaLaGaceta.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("BusquedaLaGaceta.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _01_04_1970_2 {
            get {
                object obj = ResourceManager.GetObject("01-04-1970-2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2003.
        /// </summary>
        internal static string AnioFin {
            get {
                return ResourceManager.GetString("AnioFin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1912.
        /// </summary>
        internal static string AnioInicio {
            get {
                return ResourceManager.GetString("AnioInicio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 26.
        /// </summary>
        internal static string DiaFin {
            get {
                return ResourceManager.GetString("DiaFin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 04.
        /// </summary>
        internal static string DiaInicio {
            get {
                return ResourceManager.GetString("DiaInicio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O:\\.
        /// </summary>
        internal static string DiscoImagenes {
            get {
                return ResourceManager.GetString("DiscoImagenes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O:\\ARCHIVOS INDEXING\\.
        /// </summary>
        internal static string Imagenes {
            get {
                return ResourceManager.GetString("Imagenes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O:\\Archivos Indexing\\Imagenes Cortadas\\.
        /// </summary>
        internal static string ImagenesCortadas {
            get {
                return ResourceManager.GetString("ImagenesCortadas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O:\\ARCHIVOS INDEXING\\noencontrada.png.
        /// </summary>
        internal static string ImagenNoEncontrada {
            get {
                return ResourceManager.GetString("ImagenNoEncontrada", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O:\\db_lucene\\.
        /// </summary>
        internal static string IndexPath {
            get {
                return ResourceManager.GetString("IndexPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 01.
        /// </summary>
        internal static string MesFin {
            get {
                return ResourceManager.GetString("MesFin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 08.
        /// </summary>
        internal static string MesInicio {
            get {
                return ResourceManager.GetString("MesInicio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap success_opt {
            get {
                object obj = ResourceManager.GetObject("success_opt", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
