//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BusquedaLaGaceta
{
    using System;
    using System.Collections.Generic;
    
    public partial class Table_StopWord
    {
        public int ID_StopWord { get; set; }
        public string StopWord_Word { get; set; }
        public int ID_Language { get; set; }
    
        public virtual Table_Language Table_Language { get; set; }
        public virtual Table_Language Table_Language1 { get; set; }
        public virtual Table_Language Table_Language2 { get; set; }
        public virtual Table_Language Table_Language3 { get; set; }
    }
}
