//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BusquedaLaGaceta
{
    using System;
    using System.Collections.Generic;
    
    public partial class Table_Gral
    {
        public long id { get; set; }
        public Nullable<long> nro_tabla { get; set; }
        public Nullable<long> nro_item { get; set; }
        public string descripcion { get; set; }
    }
}
