//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BusquedaLaGaceta
{
    using System;
    using System.Collections.Generic;
    
    public partial class Table_ProcessedFiles
    {
        public long Id { get; set; }
        public string File_Name { get; set; }
        public Nullable<System.DateTime> Date_NewsPaper { get; set; }
        public Nullable<int> Page_Number { get; set; }
        public Nullable<System.DateTime> Creation_Date { get; set; }
        public Nullable<decimal> Year { get; set; }
        public Nullable<decimal> Number_NewsPaper { get; set; }
        public long Id_LuceneDBIndexAddress { get; set; }
        public Nullable<int> Finalized { get; set; }
    
        public virtual Table_LuceneDBIndexAddress Table_LuceneDBIndexAddress { get; set; }
        public virtual Table_LuceneDBIndexAddress Table_LuceneDBIndexAddress1 { get; set; }
    }
}
