//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BusquedaLaGaceta
{
    using System;
    using System.Collections.Generic;
    
    public partial class Table_FileType
    {
        public Table_FileType()
        {
            this.Table_File = new HashSet<Table_File>();
            this.Table_Schedule = new HashSet<Table_Schedule>();
            this.Table_Schedule1 = new HashSet<Table_Schedule>();
            this.Table_Schedule2 = new HashSet<Table_Schedule>();
            this.Table_Schedule3 = new HashSet<Table_Schedule>();
        }
    
        public int ID_FileType { get; set; }
        public string FileType_Name { get; set; }
        public string FileType_Extension { get; set; }
    
        public virtual ICollection<Table_File> Table_File { get; set; }
        public virtual ICollection<Table_Schedule> Table_Schedule { get; set; }
        public virtual ICollection<Table_Schedule> Table_Schedule1 { get; set; }
        public virtual ICollection<Table_Schedule> Table_Schedule2 { get; set; }
        public virtual ICollection<Table_Schedule> Table_Schedule3 { get; set; }
    }
}
