//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BusquedaLaGaceta
{
    using System;
    using System.Collections.Generic;
    
    public partial class Table_Schedule
    {
        public Table_Schedule()
        {
            this.Table_Schedule_LuceneDBIndexAddress = new HashSet<Table_Schedule_LuceneDBIndexAddress>();
            this.Table_Schedule_LuceneDBIndexAddress1 = new HashSet<Table_Schedule_LuceneDBIndexAddress>();
        }
    
        public int ID_Schedule { get; set; }
        public string Schedule_Name { get; set; }
        public string Schedule_RootDirectory { get; set; }
        public string Schedule_Type { get; set; }
        public string Schedule_Date { get; set; }
        public string Schedule_Time { get; set; }
        public string Schedule_Day { get; set; }
        public int Schedule_Interval { get; set; }
        public int Schedule_Frequency { get; set; }
        public int ID_FileType { get; set; }
        public int ID_User { get; set; }
    
        public virtual Table_FileType Table_FileType { get; set; }
        public virtual Table_FileType Table_FileType1 { get; set; }
        public virtual Table_FileType Table_FileType2 { get; set; }
        public virtual Table_FileType Table_FileType3 { get; set; }
        public virtual ICollection<Table_Schedule_LuceneDBIndexAddress> Table_Schedule_LuceneDBIndexAddress { get; set; }
        public virtual Table_User Table_User { get; set; }
        public virtual Table_User Table_User1 { get; set; }
        public virtual Table_User Table_User2 { get; set; }
        public virtual Table_User Table_User3 { get; set; }
        public virtual ICollection<Table_Schedule_LuceneDBIndexAddress> Table_Schedule_LuceneDBIndexAddress1 { get; set; }
    }
}
