//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BusquedaLaGaceta
{
    using System;
    using System.Collections.Generic;
    
    public partial class Table_Periods_Suplements
    {
        public int Id_Periods { get; set; }
        public int Id_Suplements { get; set; }
        public System.DateTime Date_From { get; set; }
        public System.DateTime Date_To { get; set; }
    
        public virtual Table_Suplements Table_Suplements { get; set; }
        public virtual Table_Suplements Table_Suplements1 { get; set; }
    }
}
