//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BusquedaLaGaceta
{
    using System;
    using System.Collections.Generic;
    
    public partial class Table_File
    {
        public int ID_File { get; set; }
        public string File_Name { get; set; }
        public string File_Location { get; set; }
        public Nullable<int> ID_FileType { get; set; }
    
        public virtual Table_FileType Table_FileType { get; set; }
    }
}
