//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BusquedaLaGaceta
{
    using System;
    using System.Collections.Generic;
    
    public partial class Table_TempReport
    {
        public long id { get; set; }
        public string directory { get; set; }
        public Nullable<int> numberFile { get; set; }
        public Nullable<int> numberRename { get; set; }
        public Nullable<int> roll { get; set; }
    }
}
