//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BusquedaLaGaceta
{
    using System;
    using System.Collections.Generic;
    
    public partial class Table_Log
    {
        public long id { get; set; }
        public Nullable<long> id_usuario { get; set; }
        public string periodicos { get; set; }
        public string operacion { get; set; }
        public System.DateTime fecha_hora { get; set; }
    }
}
