//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BusquedaLaGaceta
{
    using System;
    using System.Collections.Generic;
    
    public partial class Table_Schedule_LuceneDBIndexAddress
    {
        public long ID { get; set; }
        public int ID_Schedule { get; set; }
        public long ID_LuceneDBIndexAddress { get; set; }
        public Nullable<int> Finalized { get; set; }
    
        public virtual Table_LuceneDBIndexAddress Table_LuceneDBIndexAddress { get; set; }
        public virtual Table_LuceneDBIndexAddress Table_LuceneDBIndexAddress1 { get; set; }
        public virtual Table_Schedule Table_Schedule { get; set; }
        public virtual Table_Schedule Table_Schedule1 { get; set; }
    }
}
