//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BusquedaLaGaceta
{
    using System;
    using System.Collections.Generic;
    
    public partial class Table_Suplements
    {
        public Table_Suplements()
        {
            this.Table_Periods_Suplements = new HashSet<Table_Periods_Suplements>();
            this.Table_Periods_Suplements1 = new HashSet<Table_Periods_Suplements>();
        }
    
        public int Id_Suplements { get; set; }
        public string Name_Suplemnt { get; set; }
        public string Descript_Suplement { get; set; }
    
        public virtual ICollection<Table_Periods_Suplements> Table_Periods_Suplements { get; set; }
        public virtual ICollection<Table_Periods_Suplements> Table_Periods_Suplements1 { get; set; }
    }
}
